#!/usr/bin/env python

import sys

from rqt_turtlebot_slam.turtlebot_slam import turtlebot_slam
from rqt_gui.main import Main

plugin = 'rqt_turtlebot_slam'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
