#!/bin/bash
ip_of_turtlebot=$1
ip_of_master=$(hostname -I)
export ROS_MASTER_URI=http://$ip_of_turtlebot:11311
export ROS_HOSTNAME=$ip_of_master
echo $ip_of_turtlebot
echo $ip_of_master
#nohup roscore &
#ssh turtlebot@$ip_of_turtlebot 
export DISPLAY=:0
rosrun rviz rviz
