#!/usr/bin/env python

import sys

from rqt_turtlebot_houston.turtlebot_houston import turtlebot_houston
from rqt_gui.main import Main

plugin = 'rqt_turtlebot_houston'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
