#!/usr/bin/env python

import sys
from python_qt_binding.QtGui import *
from python_qt_binding.QtCore import *
from python_qt_binding.QtWidgets import *

from rqt_turtlebot_houston.turtlebot_houston import turtlebot_houston

if __name__ == '__main__':
    app = QApplication(sys.argv)

    viz = turtlebot_houston()
    viz.resize(800,600)
    viz.show()
    app.exec_()

