#!/usr/bin/env python

import sys
from python_qt_binding.QtGui import *
from python_qt_binding.QtCore import *
from python_qt_binding.QtWidgets import *

from rqt_turtlebot_houston.turtlebot_houston_bag import turtlebot_houston

if __name__ == '__main__':
    app = QApplication(sys.argv)

    main = turtlebot_houston()
    app.exec_()

